%This script animates the movements of the Earth-Sun system generated by the c++
%script. In this data set we played around with the escape velocity of the
%earth, which can be seen in the generated plot.

load earthescape.dat;         %  read data 
positions = earthescape;
%Specifying plot graphics
figure
hold on;
view(45,45);
max_val = max(max(positions(:,:)));
axis([-max_val max_val -max_val max_val -max_val max_val]);
xlabel('x-position [AU]','interpreter','latex')
ylabel('y-position [AU]','interpreter','latex')
zlabel('z-position [AU]','interpreter','latex')
title('Earth $$v_{escape} = \sqrt 8 \pi$$ - dt = 1e-5, N = 1e5','interpreter','latex')
grid on

plot3(positions(:,1), positions(:,2), positions(:,3),'.y','markersize',30);
plot3(positions(:,4), positions(:,5), positions(:,6), '-r');
plot3(positions(end,4), positions(end,5), positions(end,6), '.b','markersize',10);

%Approximate circular earth path
r=1;
teta=-pi:0.01:pi;
x=r*cos(teta);
y=r*sin(teta);
plot3(x,y,zeros(1,numel(x)), ':')

% axis equal
