%This script plots the angles generated by the c++ script
load thetas.dat;         %  read data 

plot(thetas);  
xlabel('Orbits','interpreter','latex');
ylabel('Perihelion angle','interpreter','latex');
title('Perihelion angle (dt = 1e-6, N = 3e7, 30 years)','interpreter','latex')