%This script plots the perihelion angles generated by the c++ script as a
%function of orbits.
load thetas.dat;         %  read data 

plot(thetas);  
xlabel('Orbits','interpreter','latex');
ylabel('Perihelion angle','interpreter','latex');
title('Perihelion angle (dt = 1e-6, N = 3e7, 30 years)','interpreter','latex')