%{
This script plots the two-body system generated by the C++ script. It 
plots in 2D, but can easily be modified to plot in 3D by changing from
"plot" to "plot3" and setting the z positions
%}

load ESeulerHD.dat;         %  read data 
positions = ESeulerHD;

% Specifying plot graphics
figure
hold on;

xlabel('x-position [AU]','interpreter','latex')
ylabel('y-position [AU]','interpreter','latex')
zlabel('z-position [AU]','interpreter','latex')
title('Earth-Sun System (Euler) - dt = 1e-5, N = 1e6','interpreter','latex')
grid on

plot(positions(:,1), positions(:,2),'.y','markersize',30);
plot(positions(:,4), positions(:,5), '-r');
plot(positions(end,4), positions(end,5),'.b','markersize',10);
  
axis equal
