%This script plots the multibody system generated by the c++ script. This
%latest edition restricts the data to 1/3, plotting only the inner system.
%This script can easily be modified to work with both the 2 and 3 body
%system.

load multibody.dat;         %  read data 
positions = multibody;
%Specifying plot graphics
% view(45,45);
max_val = max(max(positions(:,:)));
axis([-max_val/3 max_val/3 -max_val/3 max_val/3 -max_val/3 max_val/3]);
xlabel('x-position [AU]','interpreter','latex')
ylabel('y-position [AU]','interpreter','latex')
zlabel('z-position [AU]','interpreter','latex')
title('Inner Solar System (dt = 1e-3, N = 1e5)','interpreter','latex')
grid on
hold on;
%Plotting orbit of planets (Disregarding moon)
for i=1:3:15
    plot3(positions(:,i), positions(:,i+1), positions(:,i+2));
    end
    
for i=1:3:15
    
    plot3(positions(end,i), positions(end,i+1), positions(end,i+2),'.','markersize',10);
 end
axis equal
