
%This script animates the movements of the planets generated by the c++
%script.

load multibody.dat;         %  read data 
positions = multibody;
%Specifying plot graphics
% view(45,45);
max_val = max(max(positions(:,:)));
axis([-max_val/3 max_val/3 -max_val/3 max_val/3 -max_val/3 max_val/3]);
xlabel('x-position [AU]','interpreter','latex')
ylabel('y-position [AU]','interpreter','latex')
zlabel('z-position [AU]','interpreter','latex')
title('Inner Solar System (dt = 1e-3, N = 1e5)','interpreter','latex')
grid on

%
% Energies for Threebody system.dat
% Step: 1000000    E =    -0.004   Ek = 0.0040197    Ep =-0.0077056
% For 10m_j
% Step: 1000000    E =     -0.04   Ek =  0.041006    Ep = -0.077361
% For 1000m_j
% Step: 100000    E =        -4   Ek =     3.314    Ep =    -6.944

hold on;
%Plotting orbit of planets (Disregarding moon)
for i=1:3:15
    plot3(positions(:,i), positions(:,i+1), positions(:,i+2));
    end
    
for i=1:3:15
    
    plot3(positions(end,i), positions(end,i+1), positions(end,i+2),'.','markersize',10);
 end
axis equal
